### ISSUE TITLE
Planarity of the benzene ring not maintained in dynamics.

### ISSUE THREAD

**Issue by mayank-kohli** [alanwilter/acpype#82] opened 2022-08-25 05:09 UTC
Hi,

I have a small molecule with benzene ring, and generated parameters using the command `acpype -i file.pdb -n 0`, but in the Dynamics it is loosing its planarity, I am using Amberr99sb ff in gromacs 2021.3.

Is there any way it can be resolved?

Thank you

**Comment by lkagami** [comment] 2022-08-25 13:08
Dear user,
Please, could you send for us the file.pdb?  For this email: lucianopkagami@hotmail.com.
We will check it. Thnks,
Luciano

**Comment by alanwilter** [comment] 2022-08-25 14:42
If I do
```bash
acpype -i c1ccccc1 # benzene

echo 0 | gmx editconf -f smiles_molecule_GMX.gro -bt octahedron -d 10 -c -princ
gmx grompp -f em.mdp -c out.gro -p smiles_molecule_GMX.top -o em.tpr -v
gmx mdrun -ntmpi 1 -v -deffnm em
gmx grompp -f md.mdp -c em.gro -p smiles_molecule_GMX.top -o md.tpr -r em.gro
gmx mdrun -ntmpi 1 -v -deffnm md
vmd md.gro md.trr
```
I see no issues.

https://user-images.githubusercontent.com/3899850/186695564-a0ad20ce-eb37-4ca1-aa14-c1f71199471e.mov

**Comment by mayank-kohli** [comment] 2022-08-25 14:52
My molecule has a biphenyl ring and it is not maintaining planarity

**Comment by alanwilter** [comment] 2022-08-25 19:45
Also, how exactly did you get the topologies? How did you run `acpype`?

**Comment by mayank-kohli** [comment] 2022-08-26 00:49
So, as I Told previously i ran the command of `acpype -i file.pdb`, followed by taking the gmx topology files from the folder, adding it in to the topol.top

**Comment by alanwilter** [comment] 2022-08-26 10:21
I don't know what's happening in GitHub but I had posted this yesterday.

https://user-images.githubusercontent.com/3899850/186882852-dd81317a-d66c-47a5-8989-266bd09736e9.mov

I did the cmd you did and run it in vacuum. If it works there and it doesn't elsewhere, the problem is not the ligand topology.

Also, you really didn't describe what's your problem. @lkagami sent you that:

> Sorry, but I don't understand the planarity problem around your ligand, since a biphenyl ring can't be planar.
> Please look here:
> https://chemistry.stackexchange.com/questions/135023/why-is-biphenyl-not-planar

We can't keep guessing what's the issue because from our perspective there's none.

**Comment by mayank-kohli** [comment] 2022-08-26 10:36
![image](https://user-images.githubusercontent.com/64058587/186885708-83232ad4-7b73-4082-aa12-1e96ee3b2c36.png)

In the above image as you can see the entire phenyl ring is non-planar which is inconsistent with the sp2 hybridization of phenyl carbons.

**Comment by alanwilter** [comment] 2022-08-26 10:49
Have you calculated this fluctuation over time? Even the H linked to the ring will flex. If you see an average angle clearly out the plane, then you have an argument and again, why it would be the topology? This picture doesn't prove anything. I used the video because it's quick to emphasise what I want to show, but if you want to really dig into this, do the numbers.

I'm going to close this issue. You haven't proved your case.

**Closed by alanwilter** 2022-08-26 10:49 UTC
